
package com.example.requestpayload.batch.reader.common; // Or another suitable package

import com.example.requestpayload.service.FeedConfigService;
import org.springframework.batch.item.file.transform.DelimitedLineTokenizer;
import org.springframework.batch.item.file.transform.FieldSet;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component; // Make it a component for easy injection
import org.springframework.util.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Parses a single line of CSV-like text into a Map<String, String>
  * based on column names fetched dynamically for a given feedFileType.
   */
   @Component // Register as a Spring bean
   public class CsvCommonParser {

       private static final Logger log = LoggerFactory.getLogger(CsvCommonParser.class);

           private final FeedConfigService feedConfigService;

               // Cache column names per feed type for efficiency within the job run
                   private final ConcurrentHashMap<String, String[]> columnCache = new ConcurrentHashMap<>();

                       @Autowired // Constructor injection
                           public CsvCommonParser(FeedConfigService feedConfigService) {
                                   this.feedConfigService = Objects.requireNonNull(feedConfigService);
                                       }

                                           /**
                                                * Parses a single line into a Map using dynamically fetched columns.
                                                     *
                                                          * @param line The line of text to parse.
                                                               * @param feedFileType The type of feed, used to look up columns.
                                                                    * @param delimiter The delimiter character (e.g., ";").
                                                                         * @return A Map<String, String> where keys are column names and values are data.
                                                                              * @throws Exception If parsing fails or columns cannot be fetched.
                                                                                   */
                                                                                       public Map<String, String> parseLine(String line, String feedFileType, String delimiter) throws Exception {
                                                                                               if (!StringUtils.hasText(line)) {
                                                                                                           log.trace("Skipping blank line.");
                                                                                                                       return Collections.emptyMap(); // Return empty map for blank lines
                                                                                                                               }

                                                                                                                                       // Get column names (use cache)
                                                                                                                                               String[] columnNames = columnCache.computeIfAbsent(feedFileType, key -> {
                                                                                                                                                           log.debug("Fetching column names for feed type: {}", key);
                                                                                                                                                                       List<String> cols = feedConfigService.getExpectedColumnNames(key);
                                                                                                                                                                                   if (cols == null || cols.isEmpty()) {
                                                                                                                                                                                                   log.error("No columns configured in DB for feed type: {}", key);
                                                                                                                                                                                                                   // Throw a specific exception or handle as needed
                                                                                                                                                                                                                                   throw new RuntimeException("No columns configured for feed type: " + key);
                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                           return cols.toArray(new String[0]);
                                                                                                                                                                                                                                                                   });

                                                                                                                                                                                                                                                                           // Configure tokenizer on-the-fly for this line
                                                                                                                                                                                                                                                                                   DelimitedLineTokenizer tokenizer = new DelimitedLineTokenizer();
                                                                                                                                                                                                                                                                                           tokenizer.setDelimiter(delimiter);
                                                                                                                                                                                                                                                                                                   tokenizer.setNames(columnNames);
                                                                                                                                                                                                                                                                                                           tokenizer.setStrict(true); // Ensure token count matches column count

                                                                                                                                                                                                                                                                                                                   FieldSet fieldSet;
                                                                                                                                                                                                                                                                                                                           try {
                                                                                                                                                                                                                                                                                                                                       fieldSet = tokenizer.tokenize(line);
                                                                                                                                                                                                                                                                                                                                               } catch (Exception e) {
                                                                                                                                                                                                                                                                                                                                                           log.error("Failed to tokenize line for feed type '{}'. Line: [{}]. Error: {}", feedFileType, line, e.getMessage());
                                                                                                                                                                                                                                                                                                                                                                       throw e; // Re-throw to allow step-level fault tolerance
                                                                                                                                                                                                                                                                                                                                                                               }

                                                                                                                                                                                                                                                                                                                                                                                       // Convert FieldSet to Map
                                                                                                                                                                                                                                                                                                                                                                                               Map<String, String> dataMap = new HashMap<>();
                                                                                                                                                                                                                                                                                                                                                                                                       for (String name : fieldSet.getNames()) {
                                                                                                                                                                                                                                                                                                                                                                                                                   // Trim values during mapping
                                                                                                                                                                                                                                                                                                                                                                                                                               dataMap.put(name, fieldSet.readString(name).trim());
                                                                                                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                                                                                                               log.trace("Parsed line to map: {}", dataMap);
                                                                                                                                                                                                                                                                                                                                                                                                                                                       return dataMap;
                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                           }


               package com.example.requestpayload.batch.reader.factset;

               import com.example.requestpayload.batch.reader.common.CsvCommonParser; // Import the common parser
               import com.example.requestpayload.dto.factset.FactsetSecurityItem;
               import org.springframework.batch.item.ExecutionContext;
               import org.springframework.batch.item.ItemStreamException;
               import org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader; // Use helper base class
               import org.springframework.beans.factory.InitializingBean;
               import org.springframework.core.io.FileSystemResource;
               import org.springframework.core.io.Resource;
               import org.springframework.util.Assert;
               import org.slf4j.Logger;
               import org.slf4j.LoggerFactory;

               import java.io.BufferedReader;
               import java.io.IOException;
               import java.nio.charset.StandardCharsets;
               import java.nio.file.Files;
               import java.nio.file.Paths;
               import java.util.Map;
               import java.util.Objects;

               /**
                * ItemStreamReader for Factset files.
                 * Reads file line by line, uses CsvCommonParser to get a Map<String, String>,
                  * then maps the Map to a FactsetSecurityItem DTO applying specific logic
                   * like identifier precedence.
                    *
                     * NOTE: Bean must be @StepScope. Assumes semicolon delimiter for Factset.
                      */
                      public class FactsetClientRequestItemReader extends AbstractItemCountingItemStreamItemReader<FactsetSecurityItem>
                              implements InitializingBean {

                                  private static final Logger log = LoggerFactory.getLogger(FactsetClientRequestItemReader.class);

                                      // Dependencies injected via constructor/bean definition
                                          private final String feedFileType; // Needed to pass to parser
                                              private final String filePath;
                                                  private final CsvCommonParser commonCsvParser; // Inject the common parser

                                                      private BufferedReader bufferedReader;
                                                          private Resource resource;
                                                              private int headerLinesToSkip = 1;
                                                                  private String delimiter = ";"; // Specific to Factset

                                                                      // Keys expected in the Map returned by the parser (should match DB config)
                                                                          private static final String KEY_INTERNAL_ID = "INTERNAL_ID";
                                                                              private static final String KEY_SEDOL = "SEDOL";
                                                                                  private static final String KEY_ISIN = "ISIN";
                                                                                      private static final String KEY_CUSIP = "CUSIP";
                                                                                          private static final String KEY_FACTSET_ID = "FACTSET_ID";
                                                                                              private static final String KEY_INSTRUMENT_TYPE = "INSTRUMENT_TYPE";
                                                                                                  private static final String KEY_REQUEST_DATE = "REQUEST_DATE";
                                                                                                      private static final String KEY_OUTPUT_NAME = "OUTPUT_NAME";

                                                                                                          public FactsetClientRequestItemReader(String feedFileType, String filePath, CsvCommonParser commonCsvParser) {
                                                                                                                  this.feedFileType = Objects.requireNonNull(feedFileType, "feedFileType cannot be null");
                                                                                                                          this.filePath = Objects.requireNonNull(filePath, "filePath cannot be null");
                                                                                                                                  this.commonCsvParser = Objects.requireNonNull(commonCsvParser, "commonCsvParser cannot be null");
                                                                                                                                          // Set a name for context persistence using feedFileType for potential uniqueness if needed
                                                                                                                                                  this.setName(FactsetClientRequestItemReader.class.getSimpleName() + "_" + feedFileType);
                                                                                                                                                      }

                                                                                                                                                          @Override
                                                                                                                                                              protected FactsetSecurityItem doRead() throws Exception {
                                                                                                                                                                      String line = readLine();
                                                                                                                                                                              if (line == null) {
                                                                                                                                                                                          return null; // End of file
                                                                                                                                                                                                  }

                                                                                                                                                                                                          // Step 1: Use Common Parser to get Map
                                                                                                                                                                                                                  Map<String, String> dataMap = commonCsvParser.parseLine(line, this.feedFileType, this.delimiter);
                                                                                                                                                                                                                          if (dataMap == null || dataMap.isEmpty()) {
                                                                                                                                                                                                                                      log.warn("Common parser returned empty map for line: {}", line);
                                                                                                                                                                                                                                                  return null; // Skip this line
                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                  // Step 2: Map the Map to FactsetSecurityItem DTO (Factset Specific Logic)
                                                                                                                                                                                                                                                                          return mapDataMapToFactsetDto(dataMap);
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                  /**
                                                                                                                                                                                                                                                                                       * Reads the next line using the underlying BufferedReader.
                                                                                                                                                                                                                                                                                            */
                                                                                                                                                                                                                                                                                                protected String readLine() throws IOException {
                                                                                                                                                                                                                                                                                                        if (bufferedReader == null) {
                                                                                                                                                                                                                                                                                                                    throw new ItemStreamException("Reader must be open before it can be read.");
                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                    return this.bufferedReader.readLine();
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                            /**
                                                                                                                                                                                                                                                                                                                                                 * Maps the data from the parsed Map into the FactsetSecurityItem DTO.
                                                                                                                                                                                                                                                                                                                                                      * Contains Factset-specific logic like identifier precedence.
                                                                                                                                                                                                                                                                                                                                                           */
                                                                                                                                                                                                                                                                                                                                                               private FactsetSecurityItem mapDataMapToFactsetDto(Map<String, String> dataMap) {
                                                                                                                                                                                                                                                                                                                                                                       // --- Extract values using expected keys ---
                                                                                                                                                                                                                                                                                                                                                                               String sedol = dataMap.getOrDefault(KEY_SEDOL, "");
                                                                                                                                                                                                                                                                                                                                                                                       String isin = dataMap.getOrDefault(KEY_ISIN, "");
                                                                                                                                                                                                                                                                                                                                                                                               String cusip = dataMap.getOrDefault(KEY_CUSIP, "");
                                                                                                                                                                                                                                                                                                                                                                                                       String factsetId = dataMap.getOrDefault(KEY_FACTSET_ID, "");
                                                                                                                                                                                                                                                                                                                                                                                                               String instrumentType = dataMap.getOrDefault(KEY_INSTRUMENT_TYPE, "");
                                                                                                                                                                                                                                                                                                                                                                                                                       String internalId = dataMap.getOrDefault(KEY_INTERNAL_ID, "");
                                                                                                                                                                                                                                                                                                                                                                                                                               String requestDate = dataMap.getOrDefault(KEY_REQUEST_DATE, "");
                                                                                                                                                                                                                                                                                                                                                                                                                                       String outputName = dataMap.getOrDefault(KEY_OUTPUT_NAME, "");

                                                                                                                                                                                                                                                                                                                                                                                                                                               // --- Identifier Precedence Logic ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                       String primaryId = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                               String idType = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (!sedol.isBlank()) { primaryId = sedol; idType = "SEDOL"; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               else if (!isin.isBlank()) { primaryId = isin; idType = "ISIN"; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       else if (!cusip.isBlank()) { primaryId = cusip; idType = "CUSIP"; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               else if (!factsetId.isBlank()) { primaryId = factsetId; idType = "FACTSET_ID"; }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (primaryId == null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   log.error("No valid identifier found in data map for Internal ID: {}", internalId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               throw new IllegalArgumentException("Cannot process item, no valid identifier found for Internal ID: " + internalId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Or return null: // return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // --- Create DTO ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return new FactsetSecurityItem(primaryId, idType, instrumentType, internalId, requestDate, outputName);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               protected void doOpen() throws Exception {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Assert.state(this.filePath != null, "Input filePath must be set");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               this.resource = new FileSystemResource(this.filePath);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Assert.state(this.resource.exists(), "Input resource must exist: " + this.resource);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               Assert.state(this.resource.isReadable(), "Input resource must be readable: " + this.resource);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       log.info("Opening reader for resource: {}", this.resource);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               this.bufferedReader = Files.newBufferedReader(Paths.get(this.filePath), StandardCharsets.UTF_8); // Use appropriate charset

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // Skip Header Lines
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               for (int i = 0; i < headerLinesToSkip; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           String headerLine = readLine(); // Use the class's readLine method
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       log.debug("Skipping header line {}: {}", i + 1, headerLine);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (headerLine == null) { // EOF check
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   log.warn("End of file reached while skipping header lines.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Increment internal count if necessary (AbstractItemCountingItemStreamItemReader handles this)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // super.update(new ExecutionContext()); // Or equivalent if needed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        log.debug("Finished skipping header lines.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    protected void doClose() throws Exception {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             log.info("Closing reader for resource: {}", this.resource);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (this.bufferedReader != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   try { this.bufferedReader.close(); }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                finally { this.bufferedReader = null; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 @Override
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     public void afterPropertiesSet() throws Exception {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Validation of injected dependencies
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Assert.notNull(filePath, "filePath is required");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Assert.notNull(feedFileType, "feedFileType is required");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Assert.notNull(commonCsvParser, "commonCsvParser is required");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             // Optional: Setters for configuration if needed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 public void setHeaderLinesToSkip(int headerLinesToSkip) { this.headerLinesToSkip = headerLinesToSkip; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     public void setDelimiter(String delimiter) { this.delimiter = delimiter; }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }

 // In FactsetBatchConfig.java

 import com.example.requestpayload.batch.reader.factset.FactsetClientRequestItemReader; // Import the updated reader
 import com.example.requestpayload.batch.reader.common.CsvCommonParser; // Import the common parser
 import com.example.requestpayload.dto.factset.FactsetSecurityItem; // Reader output type
 import com.example.requestpayload.service.FeedConfigService; // Service needed by parser
 // ... other imports ...

 @Configuration
 public class FactsetBatchConfig {
     // ... Autowired dependencies (including FeedConfigService) ...
         @Autowired private FeedConfigService feedConfigService;

             // === Define the Common Parser Bean ===
                 @Bean
                     public CsvCommonParser csvCommonParser() {
                             // Inject dependencies needed by the parser (FeedConfigService)
                                     return new CsvCommonParser(feedConfigService);
                                         }

                                             // === Factset Reader Bean Definition (Uses Common Parser) ===
                                                 @Bean("factsetClientRequestItemReader")
                                                     @StepScope // ESSENTIAL for Job Parameters
                                                         public FactsetClientRequestItemReader factsetClientRequestItemReader(
                                                                     // Inject necessary Job Parameters
                                                                                 @Value("#{jobParameters['feedFileType']}") String feedFileType,
                                                                                             @Value("#{jobParameters['fullPathFileName']}") String filePath,
                                                                                                         // Inject the CsvCommonParser bean
                                                                                                                     CsvCommonParser commonCsvParser
                                                                                                                                 ) {
                                                                                                                                         // Instantiate the reader, passing dependencies
                                                                                                                                                 FactsetClientRequestItemReader reader = new FactsetClientRequestItemReader(feedFileType, filePath, commonCsvParser);
                                                                                                                                                         // reader.setDelimiter(";"); // Optional: set if not default or fetched from config
                                                                                                                                                                 // reader.setHeaderLinesToSkip(1); // Optional: set if not default
                                                                                                                                                                         return reader;
                                                                                                                                                                             }

                                                                                                                                                                                 // === Step Definition (Input type is FactsetSecurityItem) ===
                                                                                                                                                                                     @Bean("factsetFileLoadStep")
                                                                                                                                                                                         public Step factsetFileLoadStep(
                                                                                                                                                                                                     // ... JobRepository, TxManager ...
                                                                                                                                                                                                                 // Inject the specific reader bean
                                                                                                                                                                                                                             @Qualifier("factsetClientRequestItemReader") ItemReader<FactsetSecurityItem> reader,
                                                                                                                                                                                                                                         // Inject the specific processor bean
                                                                                                                                                                                                                                                     @Qualifier("factsetClientRequestItemProcessor") ItemProcessor<FactsetSecurityItem, FactsetProcessedSecurityItem> processor,
                                                                                                                                                                                                                                                                 // Inject the composite writer bean
                                                                                                                                                                                                                                                                             @Qualifier("factsetCompositeWriter") CompositeItemWriter<FactsetProcessedSecurityItem> writer,
                                                                                                                                                                                                                                                                                         // ... listeners, taskExecutor ...
                                                                                                                                                                                                                                                                                                     ) {
                                                                                                                                                                                                                                                                                                             return new StepBuilder("FACTSET-FILE-LOAD", jobRepository)
                                                                                                                                                                                                                                                                                                                             // Step processes specific DTOs
                                                                                                                                                                                                                                                                                                                                             .<FactsetSecurityItem, FactsetProcessedSecurityItem>chunk(100, transactionManager)
                                                                                                                                                                                                                                                                                                                                                             .reader(reader) // Use specific Factset reader bean
                                                                                                                                                                                                                                                                                                                                                                             .processor(processor)
                                                                                                                                                                                                                                                                                                                                                                                             .writer(writer)
                                                                                                                                                                                                                                                                                                                                                                                                             // ... listeners, taskExecutor ...
                                                                                                                                                                                                                                                                                                                                                                                                                             .build();
                                                                                                                                                                                                                                                                                                                                                                                                                                 }

                                                                                                                                                                                                                                                                                                                                                                                                                                     // ... other beans (Processor, Writers, Listeners, Job) ...
                                                                                                                                                                                                                                                                                                                                                                                                                                         // Processor bean definition should still take FactsetSecurityItem as input
                                                                                                                                                                                                                                                                                                                                                                                                                                              @Bean("factsetClientRequestItemProcessor")
                                                                                                                                                                                                                                                                                                                                                                                                                                                   @StepScope
                                                                                                                                                                                                                                                                                                                                                                                                                                                        public FactsetClientRequestItemProcessor factsetClientRequestItemProcessor(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // ... inject job params needed by processor ...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          @Value("#{jobParameters['clientRequestIdentifier']}") String reqId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   @Value("#{jobParameters['skipCache']}") String skipCache,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @Value("#{jobParameters['outputIndex']}") String outputIndex,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ProviderParamService providerParamService // Needs this service
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // Processor takes FactsetSecurityItem as input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new FactsetClientRequestItemProcessor(reqId, Boolean.parseBoolean(skipCache), outputIndex, /* providerCacheIndex? */, providerParamService);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                